package com.ysj.user.client;

import com.ysj.user.model.PartnerInfo;

public interface PartnerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_info
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    int deleteByPrimaryKey(Integer partnerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_info
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    int insert(PartnerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_info
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    int insertSelective(PartnerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_info
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    PartnerInfo selectByPrimaryKey(Integer partnerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_info
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    int updateByPrimaryKeySelective(PartnerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_info
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    int updateByPrimaryKey(PartnerInfo record);
}