package com.ysj.user.model;

import java.util.Date;

public class PartnerInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_info.partner_id
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    private Integer partnerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_info.name
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_info.short_name
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    private String shortName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_info.member_num
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    private Integer memberNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_info.email
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_info.telphone
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    private String telphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_info.mobile
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_info.fax
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    private String fax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_info.post
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    private String post;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_info.contact_address
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    private String contactAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_info.contact_name
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    private String contactName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_info.create_time
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_info.create_by
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    private Integer createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_info.update_time
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_info.update_by
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    private Integer updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_info.note
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_info.corporation_name
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    private String corporationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_info.idcard_num
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    private String idcardNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_info.idcard_pic_front
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    private String idcardPicFront;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_info.license_num
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    private String licenseNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_info.license_pic
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    private String licensePic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_info.logo
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    private String logo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_info.is_verified
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    private Boolean isVerified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_info.is_active
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    private Boolean isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_info.status
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_info.control_by_org
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    private Integer controlByOrg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_info.group
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    private Integer group;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_info.area_id
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    private Integer areaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_info.admin_id
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    private Integer adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_info.limit_swich
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    private Integer limitSwich;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_info.referee_by
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    private Integer refereeBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_info.reject_info
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    private String rejectInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partner_info.idcard_pic_back
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    private String idcardPicBack;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_info.partner_id
     *
     * @return the value of partner_info.partner_id
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public Integer getPartnerId() {
        return partnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_info.partner_id
     *
     * @param partnerId the value for partner_info.partner_id
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public void setPartnerId(Integer partnerId) {
        this.partnerId = partnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_info.name
     *
     * @return the value of partner_info.name
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_info.name
     *
     * @param name the value for partner_info.name
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_info.short_name
     *
     * @return the value of partner_info.short_name
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_info.short_name
     *
     * @param shortName the value for partner_info.short_name
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public void setShortName(String shortName) {
        this.shortName = shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_info.member_num
     *
     * @return the value of partner_info.member_num
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public Integer getMemberNum() {
        return memberNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_info.member_num
     *
     * @param memberNum the value for partner_info.member_num
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public void setMemberNum(Integer memberNum) {
        this.memberNum = memberNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_info.email
     *
     * @return the value of partner_info.email
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_info.email
     *
     * @param email the value for partner_info.email
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_info.telphone
     *
     * @return the value of partner_info.telphone
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_info.telphone
     *
     * @param telphone the value for partner_info.telphone
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_info.mobile
     *
     * @return the value of partner_info.mobile
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_info.mobile
     *
     * @param mobile the value for partner_info.mobile
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_info.fax
     *
     * @return the value of partner_info.fax
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_info.fax
     *
     * @param fax the value for partner_info.fax
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public void setFax(String fax) {
        this.fax = fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_info.post
     *
     * @return the value of partner_info.post
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public String getPost() {
        return post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_info.post
     *
     * @param post the value for partner_info.post
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public void setPost(String post) {
        this.post = post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_info.contact_address
     *
     * @return the value of partner_info.contact_address
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public String getContactAddress() {
        return contactAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_info.contact_address
     *
     * @param contactAddress the value for partner_info.contact_address
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public void setContactAddress(String contactAddress) {
        this.contactAddress = contactAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_info.contact_name
     *
     * @return the value of partner_info.contact_name
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_info.contact_name
     *
     * @param contactName the value for partner_info.contact_name
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_info.create_time
     *
     * @return the value of partner_info.create_time
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_info.create_time
     *
     * @param createTime the value for partner_info.create_time
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_info.create_by
     *
     * @return the value of partner_info.create_by
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_info.create_by
     *
     * @param createBy the value for partner_info.create_by
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_info.update_time
     *
     * @return the value of partner_info.update_time
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_info.update_time
     *
     * @param updateTime the value for partner_info.update_time
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_info.update_by
     *
     * @return the value of partner_info.update_by
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_info.update_by
     *
     * @param updateBy the value for partner_info.update_by
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_info.note
     *
     * @return the value of partner_info.note
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_info.note
     *
     * @param note the value for partner_info.note
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_info.corporation_name
     *
     * @return the value of partner_info.corporation_name
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public String getCorporationName() {
        return corporationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_info.corporation_name
     *
     * @param corporationName the value for partner_info.corporation_name
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public void setCorporationName(String corporationName) {
        this.corporationName = corporationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_info.idcard_num
     *
     * @return the value of partner_info.idcard_num
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public String getIdcardNum() {
        return idcardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_info.idcard_num
     *
     * @param idcardNum the value for partner_info.idcard_num
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public void setIdcardNum(String idcardNum) {
        this.idcardNum = idcardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_info.idcard_pic_front
     *
     * @return the value of partner_info.idcard_pic_front
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public String getIdcardPicFront() {
        return idcardPicFront;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_info.idcard_pic_front
     *
     * @param idcardPicFront the value for partner_info.idcard_pic_front
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public void setIdcardPicFront(String idcardPicFront) {
        this.idcardPicFront = idcardPicFront;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_info.license_num
     *
     * @return the value of partner_info.license_num
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public String getLicenseNum() {
        return licenseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_info.license_num
     *
     * @param licenseNum the value for partner_info.license_num
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public void setLicenseNum(String licenseNum) {
        this.licenseNum = licenseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_info.license_pic
     *
     * @return the value of partner_info.license_pic
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public String getLicensePic() {
        return licensePic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_info.license_pic
     *
     * @param licensePic the value for partner_info.license_pic
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public void setLicensePic(String licensePic) {
        this.licensePic = licensePic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_info.logo
     *
     * @return the value of partner_info.logo
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_info.logo
     *
     * @param logo the value for partner_info.logo
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public void setLogo(String logo) {
        this.logo = logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_info.is_verified
     *
     * @return the value of partner_info.is_verified
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public Boolean getIsVerified() {
        return isVerified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_info.is_verified
     *
     * @param isVerified the value for partner_info.is_verified
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public void setIsVerified(Boolean isVerified) {
        this.isVerified = isVerified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_info.is_active
     *
     * @return the value of partner_info.is_active
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_info.is_active
     *
     * @param isActive the value for partner_info.is_active
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_info.status
     *
     * @return the value of partner_info.status
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_info.status
     *
     * @param status the value for partner_info.status
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_info.control_by_org
     *
     * @return the value of partner_info.control_by_org
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public Integer getControlByOrg() {
        return controlByOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_info.control_by_org
     *
     * @param controlByOrg the value for partner_info.control_by_org
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public void setControlByOrg(Integer controlByOrg) {
        this.controlByOrg = controlByOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_info.group
     *
     * @return the value of partner_info.group
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public Integer getGroup() {
        return group;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_info.group
     *
     * @param group the value for partner_info.group
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public void setGroup(Integer group) {
        this.group = group;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_info.area_id
     *
     * @return the value of partner_info.area_id
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_info.area_id
     *
     * @param areaId the value for partner_info.area_id
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_info.admin_id
     *
     * @return the value of partner_info.admin_id
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_info.admin_id
     *
     * @param adminId the value for partner_info.admin_id
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_info.limit_swich
     *
     * @return the value of partner_info.limit_swich
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public Integer getLimitSwich() {
        return limitSwich;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_info.limit_swich
     *
     * @param limitSwich the value for partner_info.limit_swich
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public void setLimitSwich(Integer limitSwich) {
        this.limitSwich = limitSwich;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_info.referee_by
     *
     * @return the value of partner_info.referee_by
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public Integer getRefereeBy() {
        return refereeBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_info.referee_by
     *
     * @param refereeBy the value for partner_info.referee_by
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public void setRefereeBy(Integer refereeBy) {
        this.refereeBy = refereeBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_info.reject_info
     *
     * @return the value of partner_info.reject_info
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public String getRejectInfo() {
        return rejectInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_info.reject_info
     *
     * @param rejectInfo the value for partner_info.reject_info
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public void setRejectInfo(String rejectInfo) {
        this.rejectInfo = rejectInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partner_info.idcard_pic_back
     *
     * @return the value of partner_info.idcard_pic_back
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public String getIdcardPicBack() {
        return idcardPicBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partner_info.idcard_pic_back
     *
     * @param idcardPicBack the value for partner_info.idcard_pic_back
     *
     * @mbg.generated Wed Dec 07 14:48:51 CST 2016
     */
    public void setIdcardPicBack(String idcardPicBack) {
        this.idcardPicBack = idcardPicBack;
    }
}